server {
    listen 3100;
    server_name _;
    root /usr/share/nginx/html/launcher;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3101;
    server_name _;
    root /usr/share/nginx/html/finance;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3102;
    server_name _;
    root /usr/share/nginx/html/security;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3201;
    server_name _;
    root /usr/share/nginx/html/retail-governance;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3202;
    server_name _;
    root /usr/share/nginx/html/seller-storefront;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3203;
    server_name _;
    root /usr/share/nginx/html/seller-backoffice;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3204;
    server_name _;
    root /usr/share/nginx/html/settlement;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3205;
    server_name _;
    root /usr/share/nginx/html/logistics;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3206;
    server_name _;
    root /usr/share/nginx/html/intl-console;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3207;
    server_name _;
    root /usr/share/nginx/html/mx-storefront;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 3208;
    server_name _;
    root /usr/share/nginx/html/mx-ops;
    index index.html;
    location = /health { add_header Content-Type text/plain; return 200 "OK\n"; }
    location / { try_files $uri $uri/ /index.html; }
}
